import type {
  PlannedMeal,
  RecipeDeclination,
  RecipeIngredient,
} from "@/lib/types";

const BATCH = "Quantités = 1 repas. Batch : cuire ×2 par personne (2 repas).";
const LOWCAL = "Dîner low cal : féculent léger, huile ≤ 8 g, volume légumes.";

function decl(
  protein: string,
  calories: number,
  proteinG: number,
  carbsG: number,
  fatG: number,
): RecipeDeclination {
  return { protein, calories, proteinG, carbsG, fatG };
}

function ing(
  id: string,
  name: string,
  role: RecipeIngredient["role"],
  gramsAlexis: number,
  gramsElodie: number,
  notes?: string,
  visualQuantity?: string,
): RecipeIngredient {
  return { id, name, role, gramsAlexis, gramsElodie, notes, visualQuantity };
}

function meal(
  partial: Omit<PlannedMeal, "servingsPerPerson" | "theme" | "batchId" | "coverLabel"> & {
    theme?: string;
  },
): PlannedMeal {
  return {
    servingsPerPerson: 2,
    batchId: partial.id,
    coverLabel: "",
    theme: partial.theme ?? "Base",
    ...partial,
  };
}

export const WEEK_DAYS = [
  "Lundi",
  "Mardi",
  "Mercredi",
  "Jeudi",
  "Vendredi",
  "Samedi",
  "Dimanche",
] as const;

export const weeklyPlan: PlannedMeal[] = [
  meal({
    id: "mon-lunch",
    day: "Lundi",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Bowl quinoa, légumes rôtis, sauce tahini-citron",
    sharedBase: "Quinoa, courgette, poivron, oignon rouge, tahini-citron, sésame",
    appliances: ["Four", "Thermomix"],
    alexis: decl("Tofu mariné sésame", 690, 42, 72, 20),
    elodie: decl("Poulet airfryer paprika", 660, 48, 62, 18),
    lowCalorie: false,
    ingredients: [
      ing("quinoa", "Quinoa cuit", "shared", 180, 150),
      ing("courgette", "Courgette rôtie", "shared", 120, 100),
      ing("poivron", "Poivron rouge", "shared", 80, 70),
      ing("oignon", "Oignon rouge", "shared", 40, 30),
      ing("tahini", "Sauce tahini-citron", "shared", 30, 25, "Thermomix"),
      ing("sesame", "Graines de sésame", "shared", 8, 6),
      ing("tofu", "Tofu ferme mariné", "alexis", 160, 0, "Marinade, réserver au frais"),
      ing("poulet", "Poulet paprika", "elodie", 0, 140, "Airfryer"),
    ],
    steps: [
      "Cuire le quinoa (Cookeo ou casserole), refroidir pour 2 déjeuners.",
      "Rôtir courgette, poivron, oignon 25 min à 200°C. Répartir en 4 boîtes (2 pers. × 2 repas).",
      "Sauce tahini-citron au Thermomix. Réserver au frigo.",
      "Alexis : mariner le tofu, le servir froid au dernier moment.",
      "Élodie : poulet airfryer paprika, 18 min. Second batch pour le repas n°2.",
    ],
    tips: [BATCH, "Sauce à part pour que les légumes restent rôtis, pas mous."],
    cautions: [],
  }),
  meal({
    id: "mon-dinner",
    day: "Lundi",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Soupe miso, pak choi, nouilles de konjac",
    sharedBase: "Bouillon miso, pak choi, champignons, konjac, oignon nouveau",
    appliances: ["Cookeo", "Plaque"],
    alexis: decl("Edamame + tofu soyeux", 390, 28, 32, 12),
    elodie: decl("Crevettes + œuf mollet", 370, 32, 22, 12),
    lowCalorie: true,
    ingredients: [
      ing("miso", "Bouillon miso", "shared", 300, 280),
      ing("pakchoi", "Pak choi", "shared", 120, 100),
      ing("champi", "Champignons", "shared", 80, 70),
      ing("konjac", "Nouilles de konjac", "shared", 100, 80),
      ing("oignon-n", "Oignon nouveau", "shared", 15, 15),
      ing("edamame", "Edamame décortiqués", "alexis", 80, 0),
      ing("tofu-s", "Tofu soyeux", "alexis", 100, 0, "Ajouté à l'assiette"),
      ing("crevettes", "Crevettes", "elodie", 0, 90),
      ing("oeuf", "Œuf mollet", "elodie", 0, 50),
    ],
    steps: [
      "Bouillon miso + champignons au Cookeo, 8 min.",
      "Blanchir pak choi 2 min, réserver.",
      "Rincer le konjac, réchauffer 1 min à la plaque.",
      "Assembler au moment : protéines distinctes par profil.",
    ],
    tips: [LOWCAL, "Konjac rincé 2 fois pour enlever l'odeur."],
    cautions: [],
  }),
  meal({
    id: "tue-lunch",
    day: "Mardi",
    dayIndex: 1,
    mealType: "dejeuner",
    baseName: "Wraps complets, crudités, houmous maison cumin-citron",
    sharedBase: "Galettes, carotte, concombre, salade, houmous maison cumin-citron",
    appliances: ["Thermomix", "Airfryer", "KitchenAid"],
    alexis: decl("Falafels airfryer pois chiches", 640, 34, 72, 18),
    elodie: decl("Dinde rôtie", 610, 46, 58, 16),
    lowCalorie: false,
    ingredients: [
      ing("galette", "Galette complète", "shared", 70, 70),
      ing("carotte", "Carotte râpée", "shared", 60, 50, "râpé fin KitchenAid"),
      ing("concombre", "Concombre", "shared", 70, 60, "lamelles"),
      ing("salade", "Salade verte", "shared", 40, 40),
      ing("pois-h-w", "Pois chiches", "shared", 28, 22, "égouttés"),
      ing("tahini-w", "Tahini", "shared", 9, 7),
      ing("citron-w", "Citron", "shared", 6, 5, "jus"),
      ing("ail-w", "Ail", "shared", 3, 2, "1 gousse"),
      ing("cumin-w", "Cumin", "shared", 2, 1),
      ing("eau-w", "Eau", "shared", 4, 3),
      ing("falafel", "Falafels pois chiches", "alexis", 120, 0, "Airfryer"),
      ing("dinde", "Dinde rôtie", "elodie", 0, 130),
    ],
    steps: [
      "§ Cuissons Airfryer",
      "Parallèle : falafels Alexis 180°C · 14 min, dinde Élodie 180°C · 16 min. Deux vagues pour le batch ×2.",
      "§ Thermomix",
      "Houmous maison : pois chiches, tahini, citron, ail, cumin, eau. 20 sec / V6, racler, 10 sec / V6.",
      "§ Découpes KitchenAid & Assemblage",
      "Carottes râpé fin, concombre lamelles. Galettes au frigo. Assembler le wrap le matin, houmous à part.",
    ],
    tips: [BATCH, "Galettes au frigo, pas au congélateur (elles cassent)."],
    cautions: [],
  }),
  meal({
    id: "tue-dinner",
    day: "Mardi",
    dayIndex: 1,
    mealType: "diner",
    baseName: "Salade concombre, tomate, herbes, vinaigrette légère",
    sharedBase: "Concombre, tomate, menthe, persil, vinaigrette citron 8g d'huile",
    appliances: ["Plaque"],
    alexis: decl("Lentilles corail froides", 420, 26, 40, 14),
    elodie: decl("Thon au naturel", 390, 34, 18, 12),
    lowCalorie: true,
    ingredients: [
      ing("concombre2", "Concombre", "shared", 150, 130),
      ing("tomate", "Tomate", "shared", 120, 100),
      ing("menthe", "Menthe", "shared", 8, 8),
      ing("persil", "Persil plat", "shared", 8, 8),
      ing("vinaigrette", "Vinaigrette citron-huile", "shared", 12, 10),
      ing("lentilles", "Lentilles corail cuites", "alexis", 140, 0, "Froides"),
      ing("thon", "Thon au naturel égoutté", "elodie", 0, 90),
    ],
    steps: [
      "Cuire les lentilles, rincer à l'eau froide.",
      "Couper concombre / tomate, ciseler menthe + persil.",
      "Vinaigrette 8 g d'huile max par assiette.",
      "Thon ajouté à l'assiette Élodie, pas mélangé au batch commun.",
    ],
    tips: [LOWCAL, "Saler au dernier moment pour garder le croquant."],
    cautions: [],
  }),
  meal({
    id: "wed-lunch",
    day: "Mercredi",
    dayIndex: 2,
    mealType: "dejeuner",
    baseName: "Bo bun légumes, vermicelles, nuoc mam vegan maison",
    sharedBase: "Vermicelles, carotte, concombre, laitue, menthe, cacahuètes grillées",
    appliances: ["Plaque", "Airfryer"],
    alexis: decl("Tofu mariné citron-gingembre (frais)", 670, 38, 78, 16),
    elodie: decl("Bœuf sauté airfryer", 690, 49, 70, 18),
    lowCalorie: false,
    weatherNote: "Canicule — version froide, zéro four long",
    theme: "Asiatique",
    ingredients: [
      ing("vermi", "Vermicelles de riz cuits", "shared", 140, 120),
      ing("carotte3", "Carotte julienne", "shared", 60, 50),
      ing("concombre3", "Concombre", "shared", 80, 70),
      ing("laitue", "Laitue", "shared", 40, 40),
      ing("menthe2", "Menthe", "shared", 6, 6),
      ing("cacao-nuts", "Cacahuètes grillées", "shared", 10, 8),
      ing("soja-nuoc", "Sauce soja", "shared", 12, 10),
      ing("citron-nuoc", "Citron vert", "shared", 15, 12, "jus"),
      ing("ail-nuoc", "Ail", "shared", 3, 3),
      ing("agave-nuoc", "Sirop d'agave", "shared", 4, 4),
      ing("gingembre-nuoc", "Gingembre frais", "shared", 5, 4),
      ing("tofu-m", "Tofu mariné citron-gingembre", "alexis", 160, 0, "Frais"),
      ing("boeuf", "Bœuf airfryer", "elodie", 0, 130),
    ],
    steps: [
      "Trempage vermicelles, rinçage eau froide.",
      "Julienne carotte/concombre. Nuoc mam vegan maison au Thermomix : soja, citron vert, ail, agave, gingembre, 10 sec / V6.",
      "Presser le tofu, mariner, réserver au frigo.",
      "Bœuf airfryer 12 min, second batch pour le repas 2.",
    ],
    tips: [BATCH, "Plat froid : idéal canicule, aucun four long."],
    cautions: [],
  }),
  meal({
    id: "wed-dinner",
    day: "Mercredi",
    dayIndex: 2,
    mealType: "diner",
    baseName: "Gazpacho andalou + toast protéiné",
    sharedBase: "Tomate, concombre, poivron, basilic, vinaigre de xérès",
    appliances: ["Thermomix", "KitchenAid"],
    alexis: decl("Toast complet + houmous maison 40g", 360, 18, 42, 12),
    elodie: decl("Toast complet + ricotta 40g + jambon", 380, 26, 36, 12),
    lowCalorie: true,
    weatherNote: "Canicule",
    theme: "Tomate",
    ingredients: [
      ing("tomate-g", "Tomate", "shared", 220, 200, "3 pièces"),
      ing("concombre-g", "Concombre", "shared", 80, 70, "1/2 pièce"),
      ing("poivron-g", "Poivron", "shared", 50, 40, "1/2 pièce"),
      ing("basilic", "Basilic", "shared", 6, 6, "1/4 botte"),
      ing("xeres", "Vinaigre de xérès", "shared", 8, 8),
      ing("toast", "Pain complet toasté", "shared", 35, 35),
      ing("pois-h-g", "Pois chiches", "alexis", 22, 0, "égouttés"),
      ing("tahini-g", "Tahini", "alexis", 7, 0),
      ing("citron-g", "Citron", "alexis", 5, 0, "jus"),
      ing("ail-g", "Ail", "alexis", 2, 0, "1 gousse"),
      ing("cumin-g", "Cumin", "alexis", 1, 0),
      ing("eau-g", "Eau", "alexis", 3, 0),
      ing("ricotta", "Ricotta", "elodie", 0, 40),
      ing("jambon", "Jambon", "elodie", 0, 30),
    ],
    steps: [
      "§ Thermomix",
      "Gazpacho : tomates, concombre, poivron, basilic, vinaigre de xérès. 1 min / V10. Très froid 2 h.",
      "Houmous maison Alexis : pois chiches, tahini, citron, ail, cumin, eau. 20 sec / V6, racler, 10 sec / V6.",
      "§ Découpes KitchenAid & Assemblage",
      "Toasts au moment du service. Houmous Alexis / ricotta + jambon Élodie à part, jamais à l'airfryer.",
    ],
    tips: [LOWCAL, "Mixer très froid : plus de goût, moins d'huile."],
    cautions: [],
  }),
  meal({
    id: "thu-lunch",
    day: "Jeudi",
    dayIndex: 3,
    mealType: "dejeuner",
    baseName: "Bowl riz, edamame, sauce satay douce",
    sharedBase: "Riz basmati, edamame, concombre, carotte, sauce satay maison",
    appliances: ["Cookeo", "Airfryer"],
    alexis: decl("Tofu ferme mariné (frais)", 710, 46, 78, 18),
    elodie: decl("Poulet airfryer", 680, 52, 68, 16),
    lowCalorie: false,
    ingredients: [
      ing("riz", "Riz basmati cuit", "shared", 180, 150),
      ing("edamame2", "Edamame", "shared", 60, 50),
      ing("concombre4", "Concombre", "shared", 70, 60),
      ing("carotte4", "Carotte", "shared", 50, 40),
      ing("satay-sesame", "Beurre de sésame", "shared", 12, 10, undefined, "1 cs"),
      ing("satay-soja", "Sauce soja", "shared", 8, 6, undefined, "1 cs"),
      ing("satay-citron", "Citron", "shared", 8, 6, "jus", "1/2 pièce"),
      ing("satay-gingembre", "Gingembre frais", "shared", 5, 4, undefined, "1 cm"),
      ing("satay-agave", "Sirop d'agave", "shared", 4, 3, undefined, "1 cc"),
      ing("satay-ail", "Ail", "shared", 3, 2, undefined, "1 gousse"),
      ing("tofu-j", "Tofu ferme mariné", "alexis", 170, 0, "Frais"),
      ing("poulet-j", "Poulet airfryer", "elodie", 0, 150),
    ],
    steps: [
      "Riz Cookeo. Edamame 3 min.",
      "Sauce satay maison : beurre de sésame 1 cs, sauce soja 1 cs, jus de citron, gingembre 1 cm, agave 1 cc, ail. 15 sec / V6. Racler. 10 sec / V6. Pots hermétiques.",
      "Tofu mariné au frigo. Poulet airfryer 18 min × 2 batches.",
    ],
    tips: [BATCH, "Sauce satay à part, 30 g max Alexis / 25 g Élodie."],
    cautions: [],
  }),
  meal({
    id: "thu-dinner",
    day: "Jeudi",
    dayIndex: 3,
    mealType: "diner",
    baseName: "Salade de lentilles, concombre, vinaigrette citron",
    sharedBase: "Lentilles, concombre, oignon rouge, persil, citron",
    appliances: ["Cookeo"],
    alexis: decl("Feta végétale", 480, 32, 40, 14),
    elodie: decl("Feta + thon", 450, 38, 36, 14),
    lowCalorie: true,
    ingredients: [
      ing("lentilles2", "Lentilles cuites", "shared", 120, 100),
      ing("concombre5", "Concombre", "shared", 100, 90),
      ing("oignon2", "Oignon rouge", "shared", 25, 20),
      ing("persil2", "Persil", "shared", 8, 8),
      ing("citron", "Jus de citron + huile", "shared", 12, 10),
      ing("feta-v", "Feta végétale", "alexis", 40, 0),
      ing("feta", "Feta", "elodie", 0, 30),
      ing("thon2", "Thon au naturel", "elodie", 0, 60),
    ],
    steps: [
      "Lentilles Cookeo 12 min, refroidir.",
      "Assembler froides. Feta / thon au plaquage.",
    ],
    tips: [LOWCAL, "Oignon rouge 10 min dans l'eau citronnée pour l'adoucir."],
    cautions: [],
  }),
  meal({
    id: "fri-lunch",
    day: "Vendredi",
    dayIndex: 4,
    mealType: "dejeuner",
    baseName: "Pâtes complètes, sauce tomate basilic, légumes",
    sharedBase: "Penne complète, tomate, basilic, courgette, ail (Thermomix)",
    appliances: ["Thermomix", "Plaque"],
    alexis: decl("Lentilles + parmesan vegan", 720, 36, 88, 16),
    elodie: decl("Dinde + parmesan", 700, 48, 78, 16),
    lowCalorie: false,
    theme: "Italien",
    ingredients: [
      ing("penne", "Penne complète crue", "shared", 90, 80),
      ing("tomate-s", "Sauce tomate basilic", "shared", 160, 140, "Thermomix"),
      ing("courgette2", "Courgette", "shared", 100, 80),
      ing("ail", "Ail", "shared", 4, 3),
      ing("lentilles3", "Lentilles", "alexis", 120, 0),
      ing("parm-v", "Parmesan vegan", "alexis", 15, 0),
      ing("dinde2", "Dinde", "elodie", 0, 130),
      ing("parm", "Parmesan", "elodie", 0, 15),
    ],
    steps: [
      "Sauce tomate-basilic-courgette Thermomix 12 min.",
      "Pâtes al dente, rincer légèrement pour le batch.",
      "Protéines à part : lentilles / dinde. Parmesan au service.",
    ],
    tips: [BATCH, "Pâtes un peu fermes : elles finissent de cuire au réchauffage."],
    cautions: [],
  }),
  meal({
    id: "fri-dinner",
    day: "Vendredi",
    dayIndex: 4,
    mealType: "diner",
    baseName: "Omelette aux blancs / tofu soyeux, épinards",
    sharedBase: "Épinards, champignons, ciboulette",
    appliances: ["Plaque"],
    alexis: decl("Omelette tofu soyeux", 410, 30, 12, 18),
    elodie: decl("Omelette 1 œuf + 3 blancs", 390, 34, 8, 16),
    lowCalorie: true,
    ingredients: [
      ing("epinards", "Épinards", "shared", 120, 100),
      ing("champi2", "Champignons", "shared", 80, 70),
      ing("ciboulette", "Ciboulette", "shared", 5, 5),
      ing("huile", "Huile", "shared", 5, 5),
      ing("tofu-om", "Tofu soyeux", "alexis", 180, 0, "Poêler au moment du repas"),
      ing("oeufs", "1 œuf + 3 blancs", "elodie", 0, 150),
    ],
    steps: [
      "Poêler champignons + épinards (base commune).",
      "Alexis : tofu soyeux mixé, poêle minute le soir.",
      "Élodie : omelette blanche à la minute.",
    ],
    tips: [LOWCAL, "Base légumes batchable ; l'omelette se fait le soir."],
    cautions: [],
  }),
  meal({
    id: "sat-lunch",
    day: "Samedi",
    dayIndex: 5,
    mealType: "dejeuner",
    baseName: "Pizza naan, légumes grillés, roquette",
    sharedBase: "Naan, sauce tomate, poivron, oignon, olives, roquette",
    appliances: ["Four", "Airfryer"],
    alexis: decl("Fromage vegan + pois chiches croustillants", 740, 28, 82, 24),
    elodie: decl("Mozzarella + poulet restes", 760, 42, 70, 26),
    lowCalorie: false,
    theme: "Italien",
    ingredients: [
      ing("naan", "Naan", "shared", 90, 90, "2 pièces"),
      ing("sauce", "Sauce tomate", "shared", 60, 60),
      ing("poivron-p", "Poivron", "shared", 50, 50),
      ing("oignon-p", "Oignon", "shared", 30, 30),
      ing("olives", "Olives", "shared", 20, 15),
      ing("roquette", "Roquette", "shared", 20, 20),
      ing("from-v", "Fromage vegan", "alexis", 40, 0),
      ing("pois", "Pois chiches airfryer", "alexis", 80, 0),
      ing("mozza", "Mozzarella", "elodie", 0, 50),
      ing("poulet-r", "Poulet restes", "elodie", 0, 80),
    ],
    steps: [
      "Naan + sauce + légumes, four 8 min.",
      "Pois chiches airfryer croustillants (Alexis).",
      "Roquette après cuisson.",
    ],
    tips: ["Naan four 8 min. Protéines au topping."],
    cautions: [],
  }),
  meal({
    id: "sat-dinner",
    day: "Samedi",
    dayIndex: 5,
    mealType: "diner",
    baseName: "Soupe froide concombre-yaourt, herbes",
    sharedBase: "Concombre, aneth, citron, yaourt (végé / grec)",
    appliances: ["Thermomix"],
    alexis: decl("Yaourt soja + graines", 340, 20, 22, 14),
    elodie: decl("Yaourt grec + crevettes", 360, 28, 16, 12),
    lowCalorie: true,
    ingredients: [
      ing("concombre-s", "Concombre", "shared", 200, 180),
      ing("aneth", "Aneth", "shared", 6, 6),
      ing("citron2", "Citron", "shared", 10, 10),
      ing("yaourt-s", "Yaourt soja", "alexis", 150, 0),
      ing("graines", "Graines de courge", "alexis", 12, 0),
      ing("yaourt-g", "Yaourt grec 0%", "elodie", 0, 150),
      ing("crev2", "Crevettes", "elodie", 0, 70),
    ],
    steps: [
      "Mixer concombre + herbes + citron Thermomix.",
      "Yaourt selon profil, très froid.",
      "Crevettes / graines au dressage.",
    ],
    tips: [LOWCAL, "Un filet d'huile 3 g suffit, le yaourt fait le crémeux."],
    cautions: [],
  }),
  meal({
    id: "sun-lunch",
    day: "Dimanche",
    dayIndex: 6,
    mealType: "dejeuner",
    baseName: "Brunch salé — patate douce, avocat, pickles",
    sharedBase: "Patate douce airfryer, avocat, pickles, roquette",
    appliances: ["Airfryer"],
    alexis: decl("Tofu scramble curcuma", 680, 34, 62, 28),
    elodie: decl("Œufs cocotte", 650, 36, 48, 28),
    lowCalorie: false,
    ingredients: [
      ing("patate", "Patate douce", "shared", 180, 150),
      ing("avocat", "Avocat", "shared", 50, 40),
      ing("pickles", "Pickles", "shared", 30, 30),
      ing("roquette2", "Roquette", "shared", 25, 25),
      ing("scramble", "Tofu scramble curcuma", "alexis", 180, 0, "Poêle minute"),
      ing("oeufs-c", "Œufs cocotte", "elodie", 0, 120),
    ],
    steps: [
      "Patate douce airfryer 20 min (session dimanche).",
      "Scramble tofu minute. Œufs cocotte 8 min.",
      "Avocat + pickles au dressage.",
    ],
    tips: [BATCH, "Patates douces en 2 repas ; protéines à la minute."],
    cautions: [],
  }),
  meal({
    id: "sun-dinner",
    day: "Dimanche",
    dayIndex: 6,
    mealType: "diner",
    baseName: "Bouillon de légumes, vermicelles, herbes",
    sharedBase: "Bouillon, vermicelles, courgette, persil plat",
    appliances: ["Cookeo"],
    alexis: decl("Tofu soyeux", 320, 22, 28, 8),
    elodie: decl("Blanc de poulet restes", 340, 30, 24, 8),
    lowCalorie: true,
    ingredients: [
      ing("bouillon", "Bouillon de légumes", "shared", 320, 300),
      ing("vermi2", "Vermicelles", "shared", 30, 25),
      ing("courgette3", "Courgette", "shared", 80, 70),
      ing("persil3", "Persil plat", "shared", 6, 6),
      ing("tofu-b", "Tofu soyeux", "alexis", 120, 0, "Ajouté dans l'assiette"),
      ing("poulet-b", "Blanc de poulet restes", "elodie", 0, 90),
    ],
    steps: [
      "Bouillon + courgette Cookeo 10 min.",
      "Vermicelles 3 min en fin de cuisson.",
      "Persil, tofu / poulet au service.",
    ],
    tips: [LOWCAL, "Idéal lendemain de brunch : léger, hydratant."],
    cautions: [],
  }),
];

export const extraRecipes: PlannedMeal[] = [
  meal({
    id: "alt-lunch-bibimbap",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Bibimbap légumes, namul sésame, sauce soja-poire",
    sharedBase: "Riz, épinards namul, carotte, concombre, pousses de soja, sauce soja-poire-sésame",
    theme: "Coréen",
    appliances: ["Cuiseur à riz", "KitchenAid", "Thermomix"],
    alexis: decl("Tofu mariné soja-sésame (frais)", 680, 40, 78, 16),
    elodie: decl("Bœuf marinade bulgogi airfryer", 690, 50, 68, 18),
    lowCalorie: false,
    ingredients: [
      ing("riz-bi", "Riz cuit", "shared", 170, 150, "cuiseur à riz"),
      ing("epinard-bi", "Épinards", "shared", 80, 70, "1/2 botte", "namul sésame"),
      ing("carotte-bi", "Carotte", "shared", 60, 50, "1 pièce", "julienne"),
      ing("concombre-bi", "Concombre", "shared", 70, 60, "1/2 pièce"),
      ing("pousses-bi", "Pousses de soja", "shared", 50, 40),
      ing("soja-bi", "Sauce soja", "shared", 18, 16, "1 cs"),
      ing("poire-bi", "Poire", "shared", 40, 35, "1/4 pièce", "marinade"),
      ing("sesame-bi", "Huile de sésame", "shared", 8, 6, "1/2 cs"),
      ing("ail-bi", "Ail", "shared", 4, 4, "1 gousse"),
      ing("gingembre-bi", "Gingembre frais", "shared", 6, 5, "1 cm"),
      ing("tofu-bi", "Tofu ferme", "alexis", 160, 0, "1/2 bloc", "mariné cru"),
      ing("boeuf-bi", "Bœuf", "elodie", 0, 130, "marinade bulgogi, airfryer"),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Riz : cuiseur à riz.",
      "§ Thermomix",
      "Sauce soja-poire : poire, sauce soja, ail, gingembre, huile de sésame. 10 sec / V7. Pots.",
      "§ Découpes KitchenAid & Assemblage",
      "Carotte : râpé fin. Concombre : lamelles. Épinards : namul (blanchis, essorés, sésame). Boîtes : riz, namul, crudités, pousses. Tofu mariné cru Alexis / bœuf airfryer 180°C · 10 min Élodie. Sauce au pot.",
    ],
    tips: [BATCH, "Namul et sauce à part pour garder le croquant."],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-japchae",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Japchae, épinards, champignons, sauce soja-sésame",
    sharedBase: "Nouilles de patate douce, épinards, champignon, carotte, sauce soja-sésame",
    theme: "Coréen",
    appliances: ["Plaque", "KitchenAid", "Airfryer"],
    alexis: decl("Tofu mariné soja-sésame (frais)", 670, 38, 80, 14),
    elodie: decl("Poulet soja-sésame airfryer", 680, 48, 70, 16),
    lowCalorie: false,
    ingredients: [
      ing("noodle-ja", "Nouilles de patate douce", "shared", 80, 70, "sec"),
      ing("epinard-ja", "Épinards", "shared", 70, 60, "1/2 botte"),
      ing("champ-ja", "Champignons de Paris", "shared", 80, 70, "4 pièces"),
      ing("carotte-ja", "Carotte", "shared", 50, 40, "1 pièce"),
      ing("soja-ja", "Sauce soja", "shared", 16, 14, "1 cs"),
      ing("sesame-ja", "Huile de sésame", "shared", 8, 6, "1/2 cs"),
      ing("ail-ja", "Ail", "shared", 3, 3, "1 gousse"),
      ing("agave-ja", "Sirop d'agave", "shared", 4, 4, "1 cc"),
      ing("tofu-ja", "Tofu ferme", "alexis", 160, 0, "1/2 bloc"),
      ing("poulet-ja", "Poulet", "elodie", 0, 130, "airfryer"),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Nouilles de patate douce : eau 6 min, rincer froid. Épinards : 1 min, essorer.",
      "§ Découpes KitchenAid & Assemblage",
      "Carotte : julienne. Champignons : lamelles, poêle 4 min. Sauce soja-sésame-ail-agave au fouet (pot). Tofu mariné cru Alexis / poulet 180°C · 12 min Élodie. Mélanger nouilles + namul + sauce au service.",
    ],
    tips: [BATCH],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-kimbap",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Kimbap, riz, nori, daikon, marinade soja-sésame",
    sharedBase: "Riz, nori, concombre, carotte, daikon, épinards, marinade soja-sésame",
    theme: "Coréen",
    appliances: ["Cuiseur à riz", "KitchenAid"],
    alexis: decl("Tofu mariné soja-sésame (frais)", 660, 36, 82, 14),
    elodie: decl("Œuf omelette + dinde", 670, 42, 74, 16),
    lowCalorie: false,
    ingredients: [
      ing("riz-ki", "Riz cuit", "shared", 160, 140, "cuiseur à riz"),
      ing("nori-ki", "Feuilles de nori", "shared", 6, 6, "2 feuilles"),
      ing("concombre-ki", "Concombre", "shared", 60, 50, "1/2 pièce"),
      ing("carotte-ki", "Carotte", "shared", 40, 35, "1/2 pièce"),
      ing("daikon-ki", "Daikon", "shared", 40, 35, "bâtonnets"),
      ing("epinard-ki", "Épinards", "shared", 40, 35),
      ing("soja-ki", "Sauce soja", "shared", 12, 10, "1 cs"),
      ing("sesame-ki", "Huile de sésame", "shared", 6, 5, "1/2 cs"),
      ing("tofu-ki", "Tofu ferme", "alexis", 150, 0, "bâtonnets marinés"),
      ing("oeuf-ki", "Œufs", "elodie", 0, 50, "1 pièce"),
      ing("dinde-ki", "Dinde", "elodie", 0, 70),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Riz : cuiseur à riz. Épinards : 1 min, essorer, sésame.",
      "§ Découpes KitchenAid & Assemblage",
      "Concombre, carotte, daikon : bâtonnets. Riz tiède + 1/2 cs huile de sésame. Rouler dans le nori. Tofu mariné Alexis / omelette + dinde Élodie. Sauce soja-sésame au pot.",
    ],
    tips: [BATCH, "Rouler juste avant de boxer pour garder le nori croustillant."],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-namul",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Namul épinards-concombre, vinaigrette soja-sésame",
    sharedBase: "Épinards, concombre, pousses de soja, vinaigrette soja-sésame-ail",
    theme: "Coréen",
    appliances: ["Plaque", "KitchenAid"],
    alexis: decl("Tofu mariné soja-sésame (frais)", 340, 24, 18, 12),
    elodie: decl("Blanc de poulet restes", 350, 32, 14, 10),
    lowCalorie: true,
    ingredients: [
      ing("epinard-na", "Épinards", "shared", 120, 110, "1 botte"),
      ing("concombre-na", "Concombre", "shared", 100, 90, "1/2 pièce"),
      ing("pousses-na", "Pousses de soja", "shared", 60, 50),
      ing("soja-na", "Sauce soja", "shared", 10, 8, "1 cs"),
      ing("sesame-na", "Huile de sésame", "shared", 6, 5, "1/2 cs"),
      ing("ail-na", "Ail", "shared", 3, 3, "1 gousse"),
      ing("citron-na", "Citron", "shared", 10, 8, "1/4 pièce"),
      ing("tofu-na", "Tofu ferme", "alexis", 120, 0),
      ing("poulet-na", "Poulet", "elodie", 0, 90),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Épinards : 1 min, essorer fort. Pousses : 2 min, rafraîchir.",
      "§ Découpes KitchenAid & Assemblage",
      "Concombre : lamelles. Vinaigrette soja-sésame-ail-citron au fouet. Namul en assiette, tofu mariné Alexis / poulet Élodie. Pas de riz le soir.",
    ],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-banchan",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Banchan concombre, pousses de soja, sauce soja-ail-sésame",
    sharedBase: "Concombre, pousses de soja, carotte, sauce soja-ail-sésame",
    theme: "Coréen",
    appliances: ["KitchenAid"],
    alexis: decl("Tofu mariné soja-sésame (frais)", 330, 22, 16, 12),
    elodie: decl("Œuf mollet + dinde", 340, 28, 12, 12),
    lowCalorie: true,
    ingredients: [
      ing("concombre-ba", "Concombre", "shared", 140, 120, "1 pièce"),
      ing("pousses-ba", "Pousses de soja", "shared", 70, 60),
      ing("carotte-ba", "Carotte", "shared", 40, 35, "1/2 pièce"),
      ing("soja-ba", "Sauce soja", "shared", 10, 8, "1 cs"),
      ing("sesame-ba", "Huile de sésame", "shared", 6, 5, "1/2 cs"),
      ing("ail-ba", "Ail", "shared", 3, 3, "1 gousse"),
      ing("vinaigre-ba", "Vinaigre de riz", "shared", 8, 6, "1/2 cs"),
      ing("tofu-ba", "Tofu ferme", "alexis", 120, 0),
      ing("oeuf-ba", "Œuf", "elodie", 0, 50, "1 pièce"),
      ing("dinde-ba", "Dinde", "elodie", 0, 50),
    ],
    steps: [
      "§ Découpes KitchenAid & Assemblage",
      "Concombre : lamelles. Carotte : râpé fin. Pousses rincées. Sauce soja-ail-sésame-vinaigre au fouet. Assiette de banchan, tofu mariné Alexis / œuf mollet + dinde Élodie.",
    ],
    tips: [LOWCAL, "Banchan très froid 30 min."],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-thai",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Bowl riz jasmin, légumes vapeur, sauce gingembre-citron",
    sharedBase: "Riz jasmin, brocoli tige, carotte, gingembre",
    theme: "Thaï",
    appliances: ["Cookeo", "Airfryer"],
    alexis: decl("Tofu mariné soja-citron (frais)", 680, 40, 74, 16),
    elodie: decl("Poulet lemongrass airfryer", 670, 50, 64, 16),
    lowCalorie: false,
    ingredients: [
      ing("riz-j", "Riz jasmin cuit", "shared", 170, 150),
      ing("brocoli", "Brocoli tige", "shared", 100, 90),
      ing("carotte-t", "Carotte", "shared", 50, 40),
      ing("gingembre", "Sauce gingembre-citron", "shared", 25, 20),
      ing("tofu-t", "Tofu mariné", "alexis", 160, 0, "Frais"),
      ing("poulet-t", "Poulet lemongrass", "elodie", 0, 140),
    ],
    steps: [
      "Riz Cookeo. Légumes vapeur 6 min.",
      "Sauce gingembre-citron-soja, 10 sec / V6.",
      "Tofu froid. Poulet airfryer.",
    ],
    tips: [BATCH, "Lemongrass + gingembre frais."],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-tomato",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Orzo, tomates rôties, basilic, olives",
    sharedBase: "Orzo complet, tomate, basilic, olive, courgette",
    theme: "Tomate",
    appliances: ["Four", "Plaque"],
    alexis: decl("Pois chiches rôtis + tofu frais", 700, 38, 84, 18),
    elodie: decl("Dinde + mozzarella", 690, 48, 72, 18),
    lowCalorie: false,
    ingredients: [
      ing("orzo", "Orzo complet cuit", "shared", 170, 150),
      ing("tomate-r", "Tomates rôties", "shared", 140, 120),
      ing("basilic2", "Basilic", "shared", 8, 8),
      ing("olive2", "Olives", "shared", 15, 12),
      ing("pois2", "Pois chiches rôtis", "alexis", 80, 0),
      ing("tofu-or", "Tofu frais", "alexis", 100, 0),
      ing("dinde3", "Dinde", "elodie", 0, 130),
      ing("mozza2", "Mozzarella", "elodie", 0, 30),
    ],
    steps: [
      "Tomates + courgette 25 min four.",
      "Orzo al dente. Assembler tiède.",
      "Tofu frais Alexis. Dinde Élodie.",
    ],
    tips: [BATCH],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-bowl",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Bowl sarrasin, betterave, concombre, sauce yaourt-citron",
    sharedBase: "Sarrasin, betterave, concombre, roquette, aneth",
    theme: "Bowl",
    appliances: ["Cookeo"],
    alexis: decl("Edamame + tofu mariné", 660, 40, 68, 16),
    elodie: decl("Poulet restes + yaourt grec", 650, 48, 58, 14),
    lowCalorie: false,
    ingredients: [
      ing("sarrasin", "Sarrasin cuit", "shared", 160, 140),
      ing("betterave", "Betterave", "shared", 80, 70),
      ing("concombre-b", "Concombre", "shared", 70, 60),
      ing("aneth-b", "Aneth", "shared", 5, 5),
      ing("edamame-b", "Edamame", "alexis", 80, 0),
      ing("tofu-b2", "Tofu mariné", "alexis", 120, 0),
      ing("poulet-b2", "Poulet", "elodie", 0, 130),
      ing("yaourt-b", "Yaourt grec", "elodie", 0, 40),
    ],
    steps: ["Sarrasin Cookeo.", "Betterave en dés, sauce yaourt-citron.", "Protéines à part."],
    tips: [BATCH, "Betterave cuite sous-vide pour gagner du temps."],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-miso",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Consommé gingembre, pak choi, tofu soyeux / poisson",
    sharedBase: "Bouillon gingembre, pak choi, champignon, oignon nouveau",
    theme: "Asiatique",
    appliances: ["Cookeo"],
    alexis: decl("Tofu soyeux + edamame", 350, 26, 20, 10),
    elodie: decl("Cabillaud vapeur", 340, 32, 12, 8),
    lowCalorie: true,
    ingredients: [
      ing("bouillon-g", "Bouillon gingembre", "shared", 320, 300),
      ing("pak2", "Pak choi", "shared", 100, 90),
      ing("champi3", "Champignons", "shared", 60, 50),
      ing("tofu-c", "Tofu soyeux", "alexis", 120, 0),
      ing("eda-c", "Edamame", "alexis", 50, 0),
      ing("cabillaud", "Cabillaud", "elodie", 0, 120),
    ],
    steps: ["Bouillon Cookeo 8 min.", "Pak choi 2 min.", "Protéines au service."],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-tomato",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Carpaccio de tomates, mozzarella, basilic",
    sharedBase: "Tomates, basilic, vinaigre, huile 6g",
    theme: "Tomate",
    appliances: ["Plaque"],
    alexis: decl("Mozzarella vegan + pois chiches", 360, 18, 22, 16),
    elodie: decl("Mozzarella + jambon", 380, 26, 14, 18),
    lowCalorie: true,
    ingredients: [
      ing("tomate-c", "Tomates", "shared", 220, 200),
      ing("basilic-c", "Basilic", "shared", 8, 8),
      ing("huile-c", "Huile d'olive", "shared", 6, 6),
      ing("mozza-v", "Mozzarella vegan", "alexis", 40, 0),
      ing("pois-c", "Pois chiches", "alexis", 60, 0),
      ing("mozza-e", "Mozzarella", "elodie", 0, 40),
      ing("jambon-c", "Jambon", "elodie", 0, 35),
    ],
    steps: ["Trancher les tomates.", "Huile 6 g, basilic.", "Fromage / jambon au dressage."],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-spicy",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Salade tiède pois chiches, paprika fumé, concombre",
    sharedBase: "Pois chiches, paprika fumé, concombre, persil, citron",
    theme: "Épicé",
    appliances: ["Airfryer"],
    alexis: decl("Pois chiches extra + feta végétale", 410, 24, 38, 12),
    elodie: decl("Poulet paprika restes", 390, 34, 22, 10),
    lowCalorie: true,
    ingredients: [
      ing("pois-s", "Pois chiches", "shared", 100, 70),
      ing("paprika", "Paprika fumé", "shared", 3, 3),
      ing("concombre-sp", "Concombre", "shared", 120, 100),
      ing("feta-sp", "Feta végétale", "alexis", 35, 0),
      ing("poulet-sp", "Poulet paprika", "elodie", 0, 100),
    ],
    steps: ["Pois chiches airfryer 8 min paprika.", "Concombre froid.", "Assembler."],
    tips: [LOWCAL, "Épicé = paprika fumé + cumin."],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-afrique",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Semoule, chermoula cumin-citron, légumes croquants",
    sharedBase: "Semoule, carotte, concombre, chou rouge, menthe, chermoula cumin-citron-paprika fumé",
    theme: "Afrique",
    appliances: ["Cookeo", "Airfryer", "Thermomix", "KitchenAid"],
    alexis: decl("Pois chiches rôtis + tofu mariné frais", 690, 38, 82, 16),
    elodie: decl("Poulet yassa citron-oignon airfryer", 680, 50, 70, 16),
    lowCalorie: false,
    ingredients: [
      ing("semoule-a", "Semoule", "shared", 80, 70, "1 bol, cuisson 5 min"),
      ing("carotte-a", "Carotte", "shared", 80, 70, "2 pièces, râpé fin"),
      ing("concombre-a", "Concombre", "shared", 90, 80, "1/2 pièce, lamelles"),
      ing("chou-a", "Chou rouge", "shared", 60, 50, "1/4 chou, râpé fin"),
      ing("menthe-a", "Menthe fraîche", "shared", 10, 8, "1/2 botte"),
      ing("ail-a", "Ail", "shared", 4, 3, "1 gousse"),
      ing("cumin-a", "Cumin", "shared", 3, 2),
      ing("paprika-a", "Paprika fumé", "shared", 3, 2),
      ing("citron-a", "Citron", "shared", 30, 25, "1/2 pièce, jus"),
      ing("huile-a", "Huile d'olive", "shared", 8, 6),
      ing("pois-a", "Pois chiches", "alexis", 90, 0, "rôtis airfryer"),
      ing("tofu-a", "Tofu ferme mariné", "alexis", 140, 0, "Frais, mariné chermoula"),
      ing("poulet-a", "Poulet yassa", "elodie", 0, 140, "citron-oignon"),
      ing("oignon-a", "Oignon", "elodie", 0, 40, "1/2 pièce, yassa"),
    ],
    steps: [
      "§ Cuissons Airfryer",
      "Parallèle 190°C · 16 min : pois chiches cumin Alexis à gauche, poulet yassa Élodie à droite (oignons citronnés dans le même panier). Tofu : presser, mariner à la chermoula, réserver au frais.",
      "§ Cuissons Eau / Plaques",
      "Semoule : 80 g / pers., eau bouillante 1:1, 5 min couvert, grainer à la fourchette, filet d'huile.",
      "§ Thermomix",
      "Chermoula : ail, cumin, paprika fumé, jus de citron, huile, menthe. 10 sec / V6, racler, 5 sec / V6. Pots hermétiques.",
      "§ Découpes KitchenAid & Assemblage",
      "Carottes râpé fin, concombre lamelles, chou rouge râpé fin. Menthe ciselée. Boîtes : semoule, crudités, protéines. Chermoula à part, verser au service.",
    ],
    tips: [BATCH, "Chermoula au pot : 2 c.à.s. au service, pas plus."],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-afrique",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Salade pois chiches, chermoula menthe-citron",
    sharedBase: "Pois chiches, concombre, tomate, menthe, chermoula cumin-citron",
    theme: "Afrique",
    appliances: ["Thermomix", "KitchenAid"],
    alexis: decl("Pois chiches extra + tofu soyeux", 390, 24, 36, 12),
    elodie: decl("Thon au naturel + pois chiches", 380, 32, 28, 10),
    lowCalorie: true,
    ingredients: [
      ing("pois-ad", "Pois chiches", "shared", 90, 70, "égouttés"),
      ing("concombre-ad", "Concombre", "shared", 100, 90, "1/2 pièce, lamelles"),
      ing("tomate-ad", "Tomate", "shared", 120, 100, "2 pièces"),
      ing("menthe-ad", "Menthe fraîche", "shared", 8, 6, "1/4 botte"),
      ing("ail-ad", "Ail", "shared", 3, 2, "1 gousse"),
      ing("cumin-ad", "Cumin", "shared", 2, 2),
      ing("paprika-ad", "Paprika fumé", "shared", 2, 2),
      ing("citron-ad", "Citron", "shared", 25, 20, "1/2 pièce, jus"),
      ing("huile-ad", "Huile d'olive", "shared", 6, 5),
      ing("tofu-ad", "Tofu soyeux", "alexis", 80, 0, "dés, à l'assiette"),
      ing("thon-ad", "Thon au naturel", "elodie", 0, 70),
    ],
    steps: [
      "§ Thermomix",
      "Chermoula légère : ail, cumin, paprika fumé, citron, huile, menthe. 10 sec / V6. Pots.",
      "§ Découpes KitchenAid & Assemblage",
      "Concombre lamelles, tomates en quartiers. Pois chiches rincés, pas de cuisson. Tofu soyeux Alexis / thon Élodie au dressage. Chermoula à part.",
    ],
    tips: [LOWCAL, "Plat froid : zéro airfryer, huile ≤ 6 g."],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-yassa",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Yassa citron-oignon, riz, courgettes",
    sharedBase: "Riz, courgette, oignon, citron, moutarde, persil, paprika fumé",
    theme: "Afrique",
    appliances: ["Cookeo", "Airfryer", "Thermomix", "KitchenAid"],
    alexis: decl("Pois chiches rôtis + tofu mariné frais", 700, 40, 80, 16),
    elodie: decl("Poulet yassa airfryer", 690, 52, 68, 16),
    lowCalorie: false,
    ingredients: [
      ing("riz-y", "Riz basmati", "shared", 80, 70, "cru, Cookeo"),
      ing("courgette-y", "Courgette", "shared", 160, 140, "1 pièce, lamelles"),
      ing("oignon-y", "Oignon", "shared", 80, 70, "1 pièce"),
      ing("citron-y", "Citron", "shared", 40, 35, "1 pièce, jus"),
      ing("moutarde-y", "Moutarde", "shared", 8, 6),
      ing("persil-y", "Persil plat", "shared", 8, 6, "1/4 botte"),
      ing("paprika-y", "Paprika fumé", "shared", 3, 2),
      ing("pois-y", "Pois chiches", "alexis", 90, 0, "rôtis"),
      ing("tofu-y", "Tofu ferme mariné", "alexis", 140, 0, "Frais"),
      ing("poulet-y", "Poulet", "elodie", 0, 140),
    ],
    steps: [
      "§ Cuissons Airfryer",
      "190°C · 16 min : pois chiches Alexis, poulet Élodie marinés yassa. Tofu hors panier.",
      "§ Cuissons Eau / Plaques",
      "Riz Cookeo 12 min.",
      "§ Thermomix",
      "Sauce yassa : oignon, citron, moutarde, paprika fumé. 15 sec / V6.",
      "§ Découpes KitchenAid & Assemblage",
      "Courgette lamelles. Tofu pressé mariné, réserver au frais. Persil. Sauce à part.",
    ],
    tips: [BATCH],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-zaalouk",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Zaalouk aubergine-tomate, pois chiches, menthe",
    sharedBase: "Aubergine, tomate, pois chiches, menthe, cumin, paprika fumé",
    theme: "Afrique",
    appliances: ["Airfryer", "Thermomix", "KitchenAid"],
    alexis: decl("Pois chiches extra + tofu mariné", 680, 36, 74, 18),
    elodie: decl("Dinde + zaalouk", 670, 48, 58, 16),
    lowCalorie: false,
    ingredients: [
      ing("aubergine-z", "Aubergine", "shared", 180, 160, "1 pièce"),
      ing("tomate-z", "Tomate", "shared", 160, 140, "2 pièces"),
      ing("pois-z", "Pois chiches", "shared", 80, 60),
      ing("menthe-z", "Menthe fraîche", "shared", 10, 8, "1/2 botte"),
      ing("cumin-z", "Cumin", "shared", 3, 2),
      ing("ail-z", "Ail", "shared", 4, 3, "1 gousse"),
      ing("tofu-z", "Tofu ferme mariné", "alexis", 140, 0, "Frais"),
      ing("dinde-z", "Dinde", "elodie", 0, 130),
    ],
    steps: [
      "§ Cuissons Airfryer",
      "Aubergine 190°C · 14 min. Dinde Élodie 16 min. Tofu hors panier.",
      "§ Thermomix",
      "Zaalouk : aubergine, tomate, ail, cumin, paprika. 20 sec / V6, racler, 10 sec / V4.",
      "§ Découpes KitchenAid & Assemblage",
      "Menthe ciselée. Tofu pressé mariné au frais. Pois chiches rincés.",
    ],
    tips: [BATCH],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-mafe",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Mafé tahini-sésame, patate douce, riz",
    sharedBase: "Riz, patate douce, tahini, soja, citron, gingembre, persil",
    theme: "Afrique",
    appliances: ["Cookeo", "Airfryer", "Thermomix"],
    alexis: decl("Tofu mariné frais + edamame", 710, 42, 84, 18),
    elodie: decl("Poulet mafé tahini", 700, 52, 72, 18),
    lowCalorie: false,
    ingredients: [
      ing("riz-m", "Riz basmati", "shared", 80, 70),
      ing("patate-m", "Patate douce", "shared", 140, 120, "1 pièce"),
      ing("tahini-m", "Tahini", "shared", 18, 14),
      ing("soja-m", "Sauce soja", "shared", 12, 10),
      ing("citron-m", "Citron", "shared", 20, 16, "jus"),
      ing("gingembre-m", "Gingembre frais", "shared", 8, 6, "1 cm"),
      ing("persil-m", "Persil plat", "shared", 6, 6),
      ing("tofu-m2", "Tofu ferme mariné", "alexis", 150, 0, "Frais"),
      ing("eda-m", "Edamame", "alexis", 50, 0),
      ing("poulet-m", "Poulet", "elodie", 0, 140),
    ],
    steps: [
      "§ Cuissons Airfryer",
      "Patate douce 190°C · 18 min. Poulet Élodie. Tofu hors panier.",
      "§ Cuissons Eau / Plaques",
      "Riz Cookeo 12 min. Edamame 3 min.",
      "§ Thermomix",
      "Mafé tahini : tahini, soja, citron, gingembre, un peu d'eau. 10 sec / V6.",
      "§ Découpes KitchenAid & Assemblage",
      "Tofu pressé mariné, réserver au frais. Persil. Sauce à part.",
    ],
    tips: [BATCH, "Mafé au tahini-sésame, sauce à part."],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-kefta",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Lentilles façon kefta, persil, citron, paprika fumé",
    sharedBase: "Lentilles, persil, oignon, cumin, paprika fumé, citron",
    theme: "Afrique",
    appliances: ["Cookeo", "Airfryer", "Thermomix", "KitchenAid"],
    alexis: decl("Boulettes lentilles airfryer + tofu frais", 690, 38, 76, 16),
    elodie: decl("Kefta dinde airfryer", 680, 50, 58, 16),
    lowCalorie: false,
    ingredients: [
      ing("lentilles-k", "Lentilles", "shared", 90, 80, "crues"),
      ing("persil-k", "Persil plat", "shared", 12, 10, "1/2 botte"),
      ing("oignon-k", "Oignon", "shared", 50, 40, "1/2 pièce"),
      ing("cumin-k", "Cumin", "shared", 3, 2),
      ing("paprika-k", "Paprika fumé", "shared", 3, 2),
      ing("citron-k", "Citron", "shared", 25, 20),
      ing("tofu-k", "Tofu ferme mariné", "alexis", 120, 0, "Frais"),
      ing("dinde-k", "Dinde hachée", "elodie", 0, 130),
    ],
    steps: [
      "§ Cuissons Airfryer",
      "Boulettes lentilles Alexis + kefta dinde Élodie 180°C · 14 min. Tofu hors panier.",
      "§ Cuissons Eau / Plaques",
      "Lentilles Cookeo 12 min pour la base.",
      "§ Thermomix",
      "Vinaigrette citron-cumin-paprika. 10 sec / V6.",
      "§ Découpes KitchenAid & Assemblage",
      "Persil ciselé. Tofu pressé mariné au frais.",
    ],
    tips: [BATCH],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-yassa",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Courgettes yassa, oignons citron, persil",
    sharedBase: "Courgette, oignon, citron, moutarde, persil",
    theme: "Afrique",
    appliances: ["Airfryer", "Thermomix", "KitchenAid"],
    alexis: decl("Tofu soyeux + pois chiches", 380, 24, 32, 12),
    elodie: decl("Poulet restes yassa", 370, 32, 18, 10),
    lowCalorie: true,
    ingredients: [
      ing("courgette-yd", "Courgette", "shared", 180, 160, "1 pièce"),
      ing("oignon-yd", "Oignon", "shared", 60, 50),
      ing("citron-yd", "Citron", "shared", 30, 25),
      ing("moutarde-yd", "Moutarde", "shared", 6, 5),
      ing("persil-yd", "Persil plat", "shared", 8, 6),
      ing("pois-yd", "Pois chiches", "alexis", 70, 0),
      ing("tofu-yd", "Tofu soyeux", "alexis", 80, 0),
      ing("poulet-yd", "Poulet", "elodie", 0, 90),
    ],
    steps: [
      "§ Cuissons Airfryer",
      "Courgettes 180°C · 10 min. Poulet Élodie si besoin. Tofu soyeux hors panier.",
      "§ Thermomix",
      "Yassa léger : oignon, citron, moutarde. 10 sec / V6.",
      "§ Découpes KitchenAid & Assemblage",
      "Persil. Tofu soyeux Alexis à l'assiette.",
    ],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-zaalouk",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Zaalouk froid, concombre, menthe",
    sharedBase: "Aubergine, tomate, concombre, menthe, cumin",
    theme: "Afrique",
    appliances: ["Thermomix", "KitchenAid"],
    alexis: decl("Pois chiches + tofu soyeux", 360, 22, 34, 10),
    elodie: decl("Thon + zaalouk", 350, 30, 18, 10),
    lowCalorie: true,
    ingredients: [
      ing("aubergine-zd", "Aubergine", "shared", 120, 100),
      ing("tomate-zd", "Tomate", "shared", 100, 90, "2 pièces"),
      ing("concombre-zd", "Concombre", "shared", 100, 90, "1/2 pièce"),
      ing("menthe-zd", "Menthe fraîche", "shared", 8, 6),
      ing("cumin-zd", "Cumin", "shared", 2, 2),
      ing("pois-zd", "Pois chiches", "alexis", 60, 0),
      ing("tofu-zd", "Tofu soyeux", "alexis", 70, 0),
      ing("thon-zd", "Thon au naturel", "elodie", 0, 70),
    ],
    steps: [
      "§ Thermomix",
      "Zaalouk : aubergine cuite, tomate, cumin. 20 sec / V6. Servir froid.",
      "§ Découpes KitchenAid & Assemblage",
      "Concombre lamelles, menthe. Tofu soyeux / thon au dressage. Pas d'airfryer.",
    ],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-lentilles-cumin",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Soupe lentilles cumin-citron, persil",
    sharedBase: "Lentilles, cumin, citron, persil, carotte",
    theme: "Afrique",
    appliances: ["Cookeo", "Thermomix"],
    alexis: decl("Lentilles extra + tofu soyeux", 370, 26, 40, 8),
    elodie: decl("Lentilles + poulet restes", 360, 32, 32, 8),
    lowCalorie: true,
    ingredients: [
      ing("lentilles-s", "Lentilles", "shared", 70, 60),
      ing("carotte-s", "Carotte", "shared", 80, 70, "1 pièce"),
      ing("cumin-s", "Cumin", "shared", 3, 2),
      ing("citron-s", "Citron", "shared", 20, 16),
      ing("persil-s", "Persil plat", "shared", 8, 6),
      ing("tofu-s2", "Tofu soyeux", "alexis", 80, 0),
      ing("poulet-s", "Poulet", "elodie", 0, 80),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Lentilles + carotte Cookeo 12 min.",
      "§ Thermomix",
      "Mixer une partie du bouillon cumin-citron 10 sec / V6, recoller.",
      "§ Découpes KitchenAid & Assemblage",
      "Persil. Tofu soyeux Alexis / poulet Élodie au service.",
    ],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-tian-provence",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Tian provençal thym-romarin, quinoa",
    sharedBase: "Courgette, tomate, aubergine, thym, romarin, quinoa, vinaigrette moutarde-citron",
    theme: "Français",
    appliances: ["Four", "Cuiseur à riz", "Thermomix", "KitchenAid", "Airfryer"],
    alexis: decl("Pois chiches rôtis", 680, 32, 78, 18),
    elodie: decl("Poulet herbes de Provence", 660, 46, 62, 16),
    lowCalorie: false,
    ingredients: [
      ing("quinoa-tp", "Quinoa", "shared", 80, 70),
      ing("courgette-tp", "Courgette", "shared", 140, 120, "1 pièce"),
      ing("tomate-tp", "Tomate", "shared", 160, 140, "2 pièces"),
      ing("aubergine-tp", "Aubergine", "shared", 120, 100, "1/2 pièce"),
      ing("thym-tp", "Thym frais", "shared", 3, 3, "4 brins"),
      ing("romarin-tp", "Romarin", "shared", 2, 2, "2 brins"),
      ing("moutarde-tp", "Moutarde", "shared", 8, 6, "1 cc"),
      ing("citron-tp", "Citron", "shared", 20, 16, "1/2 pièce"),
      ing("huile-tp", "Huile d'olive", "shared", 12, 10, "1 cs"),
      ing("pois-tp", "Pois chiches", "alexis", 120, 0),
      ing("poulet-tp", "Poulet", "elodie", 0, 140),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Rincer le quinoa. Cuiseur à riz, programme quinoa (ou 2 volumes d'eau, 12 min, reposer 5 min). Égrener à la fourchette, répartir dans 4 boîtes (2 pers. × 2 repas).",
      "§ Cuissons Airfryer",
      "Pois chiches Alexis : égoutter, 1 cc huile, thym. 180°C · 12 min, secouer à mi-cuisson.",
      "Poulet Élodie : romarin, 1 pincée d'herbes de Provence. 180°C · 14 min. Tofu : hors panier.",
      "§ Thermomix",
      "Vinaigrette : moutarde 1 cc, jus de 1/2 citron, huile d'olive 1 cs, 2 brins de thym. 10 sec / V6, racler, 5 sec / V6. Deux pots (sauce à part).",
      "§ Découpes KitchenAid & Assemblage",
      "Courgette, tomate, aubergine : lamelles 3 mm KitchenAid. Dans un plat, alterner en rosace (courgette / tomate / aubergine), huile restante, thym, romarin. Four 200°C chaleur tournante · 25 min.",
      "Dressage boîtes : quinoa au fond, 4-5 lamelles de tian par repas, pois chiches Alexis / poulet Élodie sur le côté, thym ciselé. Vinaigrette au pot, filet au moment de manger.",
    ],
    tips: [BATCH, "Le tian se tient 3 jours au frais. Réchauffer 2 min à la vapeur, sauce hors du micro-ondes."],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-pistou",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Tartines pistou, tomates, basilic",
    sharedBase: "Pain, tomate, basilic, ail, huile d'olive",
    theme: "Français",
    appliances: ["Thermomix", "KitchenAid", "Four"],
    alexis: decl("Tofu mariné herbes", 640, 34, 58, 22),
    elodie: decl("Œufs mollets", 620, 32, 52, 24),
    lowCalorie: false,
    ingredients: [
      ing("pain-pi", "Pain de campagne", "shared", 80, 70, "2 tranches"),
      ing("tomate-pi", "Tomate", "shared", 160, 140, "2 pièces"),
      ing("basilic-pi", "Basilic", "shared", 15, 12, "1/2 botte"),
      ing("ail-pi", "Ail", "shared", 6, 5, "1 gousse"),
      ing("huile-pi", "Huile d'olive", "shared", 12, 10, "1 cs"),
      ing("citron-pi", "Citron", "shared", 10, 8, "1/4 pièce"),
      ing("tofu-pi", "Tofu ferme mariné", "alexis", 150, 0),
      ing("oeuf-pi", "Œufs", "elodie", 0, 100, "2 pièces"),
    ],
    steps: [
      "§ Thermomix",
      "Pistou : basilic, ail, huile d'olive, 1 cc de jus de citron. 15 sec / V6, racler, 10 sec / V6. Pot hermétique.",
      "§ Cuissons Eau / Plaques",
      "Œufs Élodie : 7 min à l'eau frémissante, glaçon. Tofu Alexis : presser, mariner 1 cs pistou, réserver au frais.",
      "§ Découpes KitchenAid & Assemblage",
      "Tomates : lamelles 4 mm. Pain : 4 min à 180°C (four ou grille).",
      "Dressage : tartine, 1 cs pistou, lamelles de tomate, basilic restant. Tofu mariné Alexis à côté / œuf mollet coupé en 2 Élodie. Pistou restant au pot.",
    ],
    tips: [BATCH],
    cautions: [],
  }),
  meal({
    id: "alt-lunch-nicoise",
    day: "Slot",
    dayIndex: 0,
    mealType: "dejeuner",
    baseName: "Salade niçoise, haricots verts, olives",
    sharedBase: "Haricots verts, tomate, olive, pomme de terre, persil, vinaigrette moutarde-citron",
    theme: "Français",
    appliances: ["Cookeo", "KitchenAid", "Thermomix"],
    alexis: decl("Pois chiches + tofu", 650, 36, 62, 18),
    elodie: decl("Thon au naturel", 630, 42, 48, 16),
    lowCalorie: false,
    ingredients: [
      ing("haricot-ni", "Haricots verts", "shared", 120, 100),
      ing("tomate-ni", "Tomate", "shared", 140, 120, "2 pièces"),
      ing("olive-ni", "Olives noires", "shared", 20, 18),
      ing("pdt-ni", "Pomme de terre", "shared", 120, 100, "2 pièces"),
      ing("persil-ni", "Persil plat", "shared", 8, 6, "1/4 botte"),
      ing("moutarde-ni", "Moutarde", "shared", 8, 6, "1 cc"),
      ing("citron-ni", "Citron", "shared", 20, 16, "1/2 pièce"),
      ing("huile-ni", "Huile d'olive", "shared", 10, 8, "1 cs"),
      ing("pois-ni", "Pois chiches", "alexis", 100, 0),
      ing("tofu-ni", "Tofu ferme mariné", "alexis", 80, 0),
      ing("thon-ni", "Thon au naturel", "elodie", 0, 90),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Haricots verts : eau 8 min, rafraîchir. Pommes de terre en quartiers : eau 18 min, rafraîchir. Tofu Alexis : presser, mariner, frais.",
      "§ Thermomix",
      "Vinaigrette : moutarde 1 cc, jus de citron, huile d'olive. 10 sec / V6. Pots.",
      "§ Découpes KitchenAid & Assemblage",
      "Tomates : quartiers. Persil ciselé. Olives entières.",
      "Dressage boîtes : pommes de terre et haricots au fond, tomates, olives, persil. Pois chiches + tofu Alexis / thon Élodie. Sauce au pot, mélanger au service.",
    ],
    tips: [BATCH],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-veloute-poireaux",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Velouté poireaux, persil, croûton",
    sharedBase: "Poireau, pomme de terre, persil, thym",
    theme: "Français",
    appliances: ["Cookeo", "Thermomix"],
    alexis: decl("Tofu soyeux", 380, 22, 36, 10),
    elodie: decl("Jambon maigre", 370, 28, 28, 10),
    lowCalorie: true,
    ingredients: [
      ing("poireau-ve", "Poireau", "shared", 180, 160, "1 pièce"),
      ing("pdt-ve", "Pomme de terre", "shared", 80, 70, "1 petite"),
      ing("persil-ve", "Persil plat", "shared", 8, 6, "1/4 botte"),
      ing("thym-ve", "Thym", "shared", 2, 2, "3 brins"),
      ing("huile-ve", "Huile d'olive", "shared", 6, 5, "1 cc"),
      ing("tofu-ve", "Tofu soyeux", "alexis", 90, 0),
      ing("lardon-ve", "Jambon maigre", "elodie", 0, 50),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Poireau en rondelles, pomme de terre en dés, thym. Cookeo 12 min / vapeur ou mijoté, juste d'eau.",
      "§ Thermomix",
      "Verser légumes + bouillon. 20 sec / V6, racler, 10 sec / V6. Recoller 1/3 des dés pour la texture. Persil 5 sec / V4.",
      "§ Découpes KitchenAid & Assemblage",
      "Dressage : velouté en bol, 1 cc d'huile. Tofu soyeux en dés Alexis au centre / jambon en lanières Élodie. Persil restant. Pas de croûton le soir (low cal).",
    ],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-ratatouille",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Ratatouille légère, herbes de Provence",
    sharedBase: "Courgette, tomate, poivron, aubergine, herbes de Provence, vinaigrette citron",
    theme: "Français",
    appliances: ["Four", "KitchenAid", "Thermomix"],
    alexis: decl("Pois chiches", 360, 20, 38, 10),
    elodie: decl("Poulet restes", 350, 30, 22, 10),
    lowCalorie: true,
    ingredients: [
      ing("courgette-ra", "Courgette", "shared", 160, 140, "1 pièce"),
      ing("tomate-ra", "Tomate", "shared", 140, 120, "2 pièces"),
      ing("poivron-ra", "Poivron", "shared", 80, 70, "1/2 pièce"),
      ing("aubergine-ra", "Aubergine", "shared", 80, 70, "1/4 pièce"),
      ing("herbes-ra", "Herbes de Provence", "shared", 3, 3, "1 cc"),
      ing("citron-ra", "Citron", "shared", 16, 14, "1/2 pièce"),
      ing("huile-ra", "Huile d'olive", "shared", 8, 6, "1/2 cs"),
      ing("pois-ra", "Pois chiches", "alexis", 70, 0),
      ing("poulet-ra", "Poulet", "elodie", 0, 90),
    ],
    steps: [
      "§ Découpes KitchenAid & Assemblage",
      "Courgette, aubergine, poivron : lamelles 4 mm. Tomates : cubes.",
      "§ Cuissons Eau / Plaques",
      "Plat unique : légumes, 1/2 cs d'huile, herbes de Provence. Four 190°C chaleur tournante · 30 min, mélanger à 15 min.",
      "§ Thermomix",
      "Vinaigrette légère : jus de citron, 1 cc d'huile restante, 1 pincée d'herbes. 10 sec / V6. Pot.",
      "Dressage : ratatouille en assiette creuse (pas de féculent le soir). Pois chiches Alexis / poulet Élodie sur le dessus. Filet de vinaigrette et herbes au service.",
    ],
    tips: [LOWCAL],
    cautions: [],
  }),
  meal({
    id: "alt-dinner-lentilles-puy",
    day: "Slot",
    dayIndex: 0,
    mealType: "diner",
    baseName: "Lentilles du Puy, carottes, thym",
    sharedBase: "Lentilles du Puy, carotte, thym, persil, vinaigrette moutarde-vinaigre",
    theme: "Français",
    appliances: ["Cookeo", "Thermomix", "KitchenAid"],
    alexis: decl("Tofu soyeux", 370, 26, 40, 8),
    elodie: decl("Œuf mollet", 360, 28, 32, 10),
    lowCalorie: true,
    ingredients: [
      ing("lentilles-lp", "Lentilles du Puy", "shared", 70, 60),
      ing("carotte-lp", "Carotte", "shared", 80, 70, "1 pièce"),
      ing("thym-lp", "Thym", "shared", 2, 2, "3 brins"),
      ing("persil-lp", "Persil plat", "shared", 8, 6, "1/4 botte"),
      ing("moutarde-lp", "Moutarde", "shared", 6, 5, "1 cc"),
      ing("vinaigre-lp", "Vinaigre de cidre", "shared", 8, 6, "1/2 cs"),
      ing("huile-lp", "Huile d'olive", "shared", 6, 5, "1 cc"),
      ing("tofu-lp", "Tofu soyeux", "alexis", 80, 0),
      ing("oeuf-lp", "Œuf", "elodie", 0, 50, "1 pièce"),
    ],
    steps: [
      "§ Cuissons Eau / Plaques",
      "Lentilles du Puy + carotte en rondelles + thym. Cookeo 12 min. Égoutter, garder 2 cs de jus.",
      "Œuf Élodie : 7 min, glaçon.",
      "§ Thermomix",
      "Vinaigrette : moutarde, vinaigre de cidre, huile, 1 cs de jus de cuisson. 10 sec / V6.",
      "§ Découpes KitchenAid & Assemblage",
      "Persil ciselé. Dressage : lentilles tièdes en assiette, carottes visibles, vinaigrette nappée. Tofu soyeux en dés Alexis / œuf mollet coupé Élodie. Persil au dernier moment.",
    ],
    tips: [LOWCAL],
    cautions: [],
  }),
];
