import type { Database } from "@/lib/supabase/database.types";
import type { MealType, ProfileId } from "@/lib/types";

type RepasInsert = Database["public"]["Tables"]["repas"]["Insert"];
type ProfilInsert = Database["public"]["Tables"]["profils"]["Insert"];

export const SEED_PROFILS: ProfilInsert[] = [
  {
    id: "alexis",
    display_name: "Alexis",
    height_cm: 185,
    age: 34,
    sex: "male",
    diet: "vegan",
    aversions: [
      "coriandre",
      "chou-fleur",
      "piment fort",
      "pastèque",
      "fenouil",
      "seitan",
      "tempeh",
    ],
    preferences: ["épicé", "saveurs complexes", "umami"],
    start_weight_kg: 92.4,
    current_weight_kg: 82.1,
    target_weight_kg: 78.0,
    target_calories: 2300,
    target_protein_g: 160,
    target_carbs_g: 240,
    target_fat_g: 70,
    bmr: 1824,
    tdee: 2827,
    accent: "coral",
  },
  {
    id: "elodie",
    display_name: "Élodie",
    height_cm: 170,
    age: 32,
    sex: "female",
    diet: "omnivore",
    aversions: [
      "beurre de cacahuète",
      "chou-fleur",
      "piment fort",
      "mangue",
      "pastèque",
      "fenouil",
    ],
    preferences: ["frais", "herbes", "textures croquantes"],
    start_weight_kg: 74.8,
    current_weight_kg: 67.6,
    target_weight_kg: 62.0,
    target_calories: 1750,
    target_protein_g: 120,
    target_carbs_g: 170,
    target_fat_g: 55,
    bmr: 1432,
    tdee: 2219,
    accent: "violet",
  },
];

function meal(
  profile_id: ProfileId,
  date: string,
  type: MealType,
  heure: string,
  nom: string,
  calories: number,
  proteines_g: number,
  glucides_g: number,
  lipides_g: number,
  items: string[],
  extra?: Partial<RepasInsert>,
): RepasInsert {
  return {
    profile_id,
    date,
    type,
    heure,
    nom,
    calories,
    proteines_g,
    glucides_g,
    lipides_g,
    items,
    source: extra?.source ?? "plan",
    is_planned: extra?.is_planned ?? false,
    low_calorie: extra?.low_calorie ?? false,
    proteine: extra?.proteine ?? null,
    notes: extra?.notes ?? null,
  };
}

export function buildTodaySeedMeals(today: string): RepasInsert[] {
  return [
    meal(
      "alexis",
      today,
      "dejeuner",
      "12:35",
      "Bowl riz, tofu mariné, edamame, sauce satay douce",
      710,
      46,
      78,
      22,
      ["Riz basmati 90g sec", "Tofu ferme 180g (frais)", "Edamame 80g", "Sauce satay 20g"],
      { proteine: "Tofu ferme mariné (frais)" },
    ),
    meal(
      "alexis",
      today,
      "diner",
      "20:15",
      "Salade de lentilles, concombre, feta végétale, vinaigrette citron",
      480,
      32,
      48,
      16,
      ["Lentilles", "Concombre", "Feta végétale", "Citron"],
      { low_calorie: true, proteine: "Feta végétale", notes: "Dîner low calorie · tofu mariné" },
    ),
    meal(
      "elodie",
      today,
      "dejeuner",
      "12:35",
      "Bowl riz, poulet airfryer, edamame, sauce satay douce",
      680,
      52,
      68,
      18,
      ["Riz basmati 80g sec", "Poulet 150g", "Edamame 80g", "Sauce satay 15g"],
      { proteine: "Poulet airfryer" },
    ),
    meal(
      "elodie",
      today,
      "diner",
      "20:15",
      "Salade de lentilles, concombre, feta, thon, vinaigrette citron",
      450,
      38,
      36,
      14,
      ["Lentilles", "Concombre", "Feta", "Thon"],
      { low_calorie: true, proteine: "Feta + thon", notes: "Dîner low calorie" },
    ),
  ];
}

export function seedMealFor(profileId: ProfileId, date: string, type: MealType) {
  return buildTodaySeedMeals(date).find((row) => row.profile_id === profileId && row.type === type);
}

export function buildYesterdaySeedMeals(yesterday: string): RepasInsert[] {
  return [
    meal(
      "alexis",
      yesterday,
      "petit-dejeuner",
      "08:00",
      "Smoothie soja, banane, beurre de sésame",
      390,
      22,
      48,
      12,
      ["Lait soja 250ml", "Banane", "Tahini 12g"],
    ),
    meal(
      "alexis",
      yesterday,
      "dejeuner",
      "12:50",
      "Wraps complets, falafels airfryer, houmous",
      640,
      34,
      72,
      18,
      ["Galette", "Falafels", "Houmous", "Crudités"],
    ),
    meal(
      "elodie",
      yesterday,
      "petit-dejeuner",
      "08:10",
      "Œufs brouillés, pain complet, tomate",
      410,
      28,
      32,
      16,
      ["Œufs 2", "Pain 40g", "Tomate"],
    ),
    meal(
      "elodie",
      yesterday,
      "dejeuner",
      "12:50",
      "Wraps complets, dinde, houmous",
      610,
      46,
      58,
      16,
      ["Galette", "Dinde", "Houmous", "Crudités"],
    ),
  ];
}
